---
- name: Enable forward
  shell: 'echo -e "net.bridge.bridge-nf-call-ip6tables=1\nnet.bridge.bridge-nf-call-iptables=1" > /etc/sysctl.d/k8s.conf; sysctl --system'

- name: Install ntp, docker-ce and kube* 
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - "ntp"
  - "docker-ce"
  - "kubectl" 
  - "kubeadm" 
  - "kubelet"

- name: Add insecure registry IP
  shell: sed -i 's/sock$/& --insecure-registry={{registry_ip}}:5000/' /usr/lib/systemd/system/docker.service; echo -e "{\n \"insecure-registry\":[\"{{registry_ip}}:5000\"] \n}" > /etc/docker/daemon.json
  tags: inse

- name: Daemon Reload
  shell: "systemctl daemon-reload"

- name: Start docker
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Enable kubelet
  service: 
    name: kubelet
    state: restarted
    enabled: yes



