- name: Rsync time
  shell: "service ntpd stop; ntpdate {{ntp_server}}"
  tags: modname    

- name: Copy tsc
  copy:
    src: files/tsc
    dest: /root/


- name: K8S nodes init
  shell: "TOKEN=$(cat /root/tsc|awk 'NR==1'); SHA=$(cat /root/tsc|awk 'NR==2'); kubeadm join {{vip}}:{{port}} --token $TOKEN --discovery-token-ca-cert-hash sha256:$SHA --v=5" 


- name: Clean job
  shell: "rm -rf /root/tsc"
